'use client';
import { useRef,useState } from 'react'; import { Trash } from '@phosphor-icons/react'; import type {Job,JobInput} from '../lib/types';
import { Dialog as DialogRoot, DialogContent, DialogTitle, DialogDescription } from './ui/dialog';
import { useUnsavedWarning } from '../lib/use-unsaved-warning';
export function Dialog({title,description,onClose,children,dirty=false}:{title:string;description?:string;onClose:()=>void;children:React.ReactNode;dirty?:boolean}) {
  const opener = useRef<HTMLElement | null>(typeof document === 'undefined' ? null : document.activeElement as HTMLElement);
  const [discard, setDiscard] = useState(false);
  useUnsavedWarning(dirty);
  const close = () => { if (dirty) setDiscard(true); else onClose(); };
  return <DialogRoot open onOpenChange={open => { if (!open) close(); }}>
    <DialogContent className="editor-dialog" onClickCapture={event => { if (dirty && (event.target as HTMLElement).closest('[data-dialog-dismiss]')) { event.preventDefault(); event.stopPropagation(); close(); } }} onCloseAutoFocus={event => { event.preventDefault(); opener.current?.focus(); }}>
      <header className="dialog-header"><div><DialogTitle>{title}</DialogTitle><DialogDescription className={description ? undefined : 'sr-only'}>{description || title}</DialogDescription></div></header>
      {discard && <div className="discard-notice" role="alert"><p>You have unsaved changes. Discard them?</p><button type="button" className="secondary-button" onClick={() => setDiscard(false)}>Keep editing</button><button type="button" className="danger-button" onClick={onClose}>Discard changes</button></div>}
      {children}
    </DialogContent>
  </DialogRoot>;
}
const blank:JobInput={title:'',company:'',location:null,description:null,source_url:null,notes:null};
export function JobEditor({job,onClose,onSave}:{job?:Job;onClose:()=>void;onSave:(v:JobInput)=>Promise<void>}){const [dirty,setDirty]=useState(false);const [error,setError]=useState('');const [pending,setPending]=useState(false);const v=job||blank;async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(pending)return;const d=new FormData(e.currentTarget);const text=(k:string)=>String(d.get(k)||'').trim();const source=text('source_url');if(source){try{if(!['http:','https:'].includes(new URL(source).protocol))throw 0}catch{setError('Use a complete HTTP or HTTPS link.');return}}const values={title:text('title'),company:text('company'),location:text('location')||null,description:text('description')||null,source_url:source||null,notes:text('notes')||null};setPending(true);setError('');try{await onSave(values)}catch(e){setError(e instanceof Error?e.message:'Could not save the job.');setPending(false)}}return <Dialog dirty={dirty} title={job?'Edit job':'Save a job'} description="Keep the original details and your own notes together." onClose={onClose}><form onSubmit={submit} onChange={() => setDirty(true)}><div className="form-body"><div className="form-grid"><label>Job title <span className="required">*</span><input name="title" defaultValue={v.title} required maxLength={200} autoFocus/></label><label>Company <span className="required">*</span><input name="company" defaultValue={v.company} required maxLength={200}/></label></div><label>Location<input name="location" defaultValue={v.location||''} maxLength={300}/></label><label>Original posting URL<input name="source_url" type="url" defaultValue={v.source_url||''} maxLength={2048} placeholder="https://"/></label><label>Job description<textarea name="description" rows={7} defaultValue={v.description||''} maxLength={50000}/></label><label>My notes<textarea name="notes" rows={3} defaultValue={v.notes||''} maxLength={20000}/></label>{error&&<p className="form-error" role="alert">{error}</p>}</div><footer className="dialog-footer"><button type="button" className="secondary-button" data-dialog-dismiss onClick={onClose}>Cancel</button><button disabled={pending} className="primary-button">{pending?'Saving…':'Save job'}</button></footer></form></Dialog>}
export function NotesEditor({job,onClose,onSave}:{job:Job;onClose:()=>void;onSave:(n:string|null)=>Promise<void>}){const[dirty,setDirty]=useState(false);const[pending,setPending]=useState(false);const[error,setError]=useState('');return <Dialog dirty={dirty} title="My notes" description={job.title} onClose={onClose}><form onChange={() => setDirty(true)} onSubmit={async e=>{e.preventDefault();if(pending)return;setPending(true);try{await onSave(String(new FormData(e.currentTarget).get('notes')||'').trim()||null)}catch(x){setError(x instanceof Error?x.message:'Could not save notes');setPending(false)}}}><div className="form-body"><label htmlFor="notes">Personal notes</label><textarea id="notes" name="notes" rows={7} maxLength={20000} defaultValue={job.notes||''} autoFocus/>{error&&<p className="form-error" role="alert">{error}</p>}</div><footer className="dialog-footer"><button type="button" className="secondary-button" data-dialog-dismiss onClick={onClose}>Cancel</button><button disabled={pending} className="primary-button">{pending?'Saving…':'Save notes'}</button></footer></form></Dialog>}
export function DeleteDialog({job,onClose,onDelete}:{job:Job;onClose:()=>void;onDelete:()=>Promise<void>}){const[pending,setPending]=useState(false);const[error,setError]=useState('');return <Dialog title="Delete this job?" description={`${job.title} at ${job.company}`} onClose={onClose}><div className="form-body"><p>The saved job and its notes will be permanently removed.</p>{error&&<p className="form-error" role="alert">{error}</p>}</div><footer className="dialog-footer"><button autoFocus className="secondary-button" onClick={onClose}>Keep job</button><button disabled={pending} className="danger-button" onClick={async()=>{setPending(true);try{await onDelete()}catch(x){setError(x instanceof Error?x.message:'Could not delete job');setPending(false)}}}><Trash size={19}/>{pending?'Deleting…':'Delete job'}</button></footer></Dialog>}
