'use client';
import {MeteredButton} from './MeteredButton';
import { ConfirmDialog } from './ui/confirm-dialog';
import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowClockwise, CheckCircle, Sparkle, Trash, WarningCircle } from '@phosphor-icons/react';
import { api } from '../lib/api';
import type { Job, JobFitAnalysis as Analysis, JobFitAnalysisList } from '../lib/types';

const labels: Record<string,string> = {supported:'Supported',partially_supported:'Partially supported',not_evidenced:'Not evidenced',needs_clarification:'Needs clarification',explicit_mismatch:'Explicit mismatch'};

export function JobFitAnalysis({ job }: { job: Job }) {
  const [analysis,setAnalysis]=useState<Analysis|null>(null); const [history,setHistory]=useState<Analysis[]>([]);
  const [deleting,setDeleting]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const facts=useMemo(()=>new Map(analysis?.profile_facts.map(fact=>[fact.id,fact])||[]),[analysis]);
  const load=useCallback(async()=>{try{const latest=await api<Analysis>(`/jobs/${job.id}/fit-analyses/latest`);setAnalysis(latest);const list=await api<JobFitAnalysisList>(`/jobs/${job.id}/fit-analyses?page_size=10`);setHistory(list.items)}catch{setAnalysis(null);setHistory([])}},[job.id]);
  useEffect(()=>{void load()},[load,job.description,job.updated_at]);
  async function generate(){setBusy(true);setError('');try{const made=await api<Analysis>(`/jobs/${job.id}/fit-analyses`,{method:'POST',body:JSON.stringify({idempotency_key:crypto.randomUUID()})});setAnalysis(made);await load()}catch(caught){setError(caught instanceof Error?caught.message:'Analysis failed. Try again.')}finally{setBusy(false)}}
  async function remove(item:Analysis){setDeleting(true);setError('');try{await api(`/jobs/${job.id}/fit-analyses/${item.id}`,{method:'DELETE'});if(analysis?.id===item.id)setAnalysis(null);await load()}catch(caught){setError(caught instanceof Error?caught.message:'Could not delete this analysis. Try again.')}finally{setDeleting(false)}}
  return <section className="fit-analysis" aria-labelledby="fit-heading"><div className="fit-heading-row"><div><p className="eyebrow">Advisory evidence review</p><h2 id="fit-heading">Job fit analysis</h2></div><MeteredButton feature="fit" className="primary-button" disabled={busy||deleting||!job.description?.trim()} onClick={()=>void generate()}>{busy?<ArrowClockwise className="spin" size={19}/>:<Sparkle size={19}/>} {analysis?'Reanalyze fit':'Analyze fit'}</MeteredButton></div>
    <p className="muted fit-disclosure">When you choose Analyze fit, the saved job description and relevant saved profile facts are sent to the configured AI provider. Notes, contact details, CV files and unapplied suggestions are excluded. Results are advisory, not an ATS score.</p>
    {!job.description?.trim()&&<div className="fit-prerequisite"><WarningCircle size={20}/>Save a job description before analyzing fit.</div>}{busy&&<p role="status" aria-live="polite">Analyzing saved evidence…</p>}{error&&<div className="form-error" role="alert">{error} <Link href="/profile">Review profile</Link></div>}
    {analysis?.result?.missing_skills?.length ? <section className="fit-guidance" aria-label="Skills not evidenced in your saved profile"><h3>Not evidenced in your saved profile</h3><ul>{analysis.result.missing_skills.map(item=><li key={item.requirement_id}><strong>{item.skill}</strong> ({item.importance}) <blockquote>{item.job_quote}</blockquote></li>)}</ul></section> : null}
    {analysis&&<><div className="fit-source-row"><span>Saved {new Date(analysis.created_at).toLocaleString()} · {analysis.provider} / {analysis.model}</span>{analysis.is_outdated&&<strong className="outdated"><WarningCircle size={18}/>Inputs changed — reanalysis needed</strong>}</div>{analysis.status==='failed'?<div className="fit-prerequisite"><WarningCircle size={20}/>{analysis.outcome_message||'Analysis failed.'}</div>:analysis.result&&<><p className="fit-summary">{analysis.result.summary}</p><div className="coverage" aria-label="Evidence coverage">{Object.entries(labels).map(([key,label])=><span key={key}><strong>{analysis.counts[key]||0}</strong>{label}</span>)}</div><div className="requirements">{analysis.result.requirements.map(requirement=><article className={`requirement is-${requirement.assessment}`} key={requirement.id}><div className="requirement-title"><h3>{requirement.text}</h3><span>{labels[requirement.assessment]}</span><small>{requirement.importance}</small></div><p>{requirement.explanation}</p><blockquote>“{requirement.job_quote}”</blockquote>{requirement.candidate_fact_ids.length>0&&<div className="candidate-evidence"><strong>Saved profile evidence</strong>{requirement.candidate_fact_ids.map(id=><p key={id}><CheckCircle size={16}/>{facts.get(id)?.value}</p>)}</div>}</article>)}</div><div className="fit-guidance"><section><h3>Strengths</h3>{analysis.result.strengths.map(item=><p key={item}>{item}</p>)}</section><section><h3>Information gaps</h3>{analysis.result.gaps.map(item=><p key={item}>{item}</p>)}</section><section><h3>Next steps</h3>{analysis.result.actions.map(item=><p key={item}>{item}</p>)}</section></div></>}</>}
    {history.length>0&&<details className="fit-history"><summary>Previous analyses ({history.length})</summary>{history.map(item=><div key={item.id}><button className="text-button" onClick={()=>setAnalysis(item)}>{new Date(item.created_at).toLocaleString()}{item.is_outdated?' · Outdated':''}</button><ConfirmDialog title="Delete this saved fit analysis?" description="This removes the saved analysis. Your job and profile are kept." confirmLabel="Delete analysis" destructive busy={deleting} onConfirm={()=>void remove(item)} trigger={<button className="icon-button" disabled={busy||deleting} aria-label={`Delete analysis from ${new Date(item.created_at).toLocaleString()}`}><Trash size={18}/></button>}/></div>)}</details>}
  </section>
}
