import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {API,bootstrapUser,accessToken,login,cleanupUser,createdUsers} from './helpers';
test.afterEach(async({request})=>{for(const email of createdUsers.splice(0))await cleanupUser(request,email);});

test('guarded interview start answer reload resume finish review delete',async({page,request})=>{
  const user=await bootstrapUser(request,'interview');const token=await accessToken(request,user);
  const headers={Authorization:`Bearer ${token}`};
  const jobResponse=await request.post(`${API}/jobs`,{headers,data:{title:'Interview engineer',company:'Synthetic',description:'Build APIs and explain database trade-offs.'}});
  expect(jobResponse.ok()).toBeTruthy();const job=await jobResponse.json();
  expect((await request.patch(`${API}/profile`,{headers,data:{headline:'Synthetic backend engineer',skills:['Python']}})).ok()).toBeTruthy();
  const python=path.resolve(process.cwd(),'..','backend','.venv','Scripts','python.exe');
  const buffer=execFileSync(python,['-c',"from docx import Document; from io import BytesIO; import sys; d=Document(); d.add_paragraph('Synthetic candidate built a booking API.'); b=BytesIO(); d.save(b); sys.stdout.buffer.write(b.getvalue())"]);
  const uploaded=await request.post(`${API}/resumes`,{headers,multipart:{file:{name:'interview-synthetic.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer}}});
  expect(uploaded.ok()).toBeTruthy();const resume=await uploaded.json();
  expect((await request.post(`${API}/resumes/${resume.id}/extract`,{headers})).ok()).toBeTruthy();
  expect((await request.post(`${API}/resumes/${resume.id}/extraction/confirm`,{headers})).ok()).toBeTruthy();
  await login(page,user);await page.goto(`/jobs/${job.id}`);
  await page.getByRole('link',{name:'Prepare interview practice'}).click();
  await page.getByLabel('Practice source').selectOption(`cv:${resume.id}`);
  await page.getByLabel('Question count').fill('2');
  await page.getByRole('button',{name:'Review information to send'}).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button',{name:'Start interview',exact:true}).click();
  await expect(page).toHaveURL(/\/interviews\/[0-9a-f-]+$/);
  await page.getByRole('button',{name:'Ask first question (AI request)'}).click();
  await expect(page.getByRole('heading',{name:'Question 1 · behavioral'})).toBeVisible();
  const first='I built a booking API and checked error cases. I have no measured performance results.';
  await page.getByLabel('Your answer').fill(first);
  await page.getByRole('button',{name:'Save answer without AI'}).click();
  await expect(page.getByText('Answer saved. No model request was sent.')).toBeVisible();
  await page.reload();await expect(page.getByLabel('Your answer')).toHaveValue(first);
  await page.getByRole('button',{name:'Submit answer and continue'}).click();
  await expect(page.getByRole('heading',{name:'Question 2 · technical'})).toBeVisible();
  await page.getByLabel('Your answer').fill('I would compare query plans and test failure cases. This is a hypothetical approach.');
  await page.getByRole('button',{name:'Finish interview and review'}).click();
  await expect(page.getByRole('heading',{name:'Interview review',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Practice priorities'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'AI-generated guidance for answer 2'})).toBeVisible();
  await expect(page.getByText('Synthetic test provider — no live model assessment.',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Delete session',exact:true}).click();
  await page.getByRole('button',{name:'Confirm delete session'}).click();
  await expect(page.getByText('No interview sessions yet.')).toBeVisible();
});
