import { grantAiConsent } from './helpers';
import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {API,bootstrapUser,accessToken,login,cleanupUser,createdUsers} from './helpers';
test.afterEach(async({request})=>{for(const email of createdUsers.splice(0))await cleanupUser(request,email);});

test.use({launchOptions:{args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']}});

for(const voice of [false,true])test(`guarded ${voice?'voice transcript review':'text'} interview start answer reload resume finish review delete`,async({page,request})=>{
  const user=await bootstrapUser(request,'interview');const token=await accessToken(request,user);
  await grantAiConsent(request, user, voice ? ['ai_interview', 'ai_voice'] : ['ai_interview']);
  const headers={Authorization:`Bearer ${token}`};
  const jobResponse=await request.post(`${API}/jobs`,{headers,data:{title:'Interview engineer',company:'Synthetic',description:'Build APIs and explain database trade-offs.'}});
  expect(jobResponse.ok()).toBeTruthy();const job=await jobResponse.json();
  expect((await request.patch(`${API}/profile`,{headers,data:{headline:'Synthetic backend engineer',skills:['Python']}})).ok()).toBeTruthy();
  const python=path.resolve(process.cwd(),'..','backend','.venv','Scripts','python.exe');
  const buffer=execFileSync(python,['-c',"from docx import Document; from io import BytesIO; import sys; d=Document(); d.add_paragraph('Synthetic candidate built a booking API.'); b=BytesIO(); d.save(b); sys.stdout.buffer.write(b.getvalue())"]);
  const uploaded=await request.post(`${API}/resumes`,{headers,multipart:{file:{name:'interview-synthetic.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer}}});
  expect(uploaded.ok()).toBeTruthy();const resume=await uploaded.json();
  expect((await request.post(`${API}/resumes/${resume.id}/extract`,{headers})).ok()).toBeTruthy();
  expect((await request.post(`${API}/resumes/${resume.id}/extraction/confirm`,{headers})).ok()).toBeTruthy();
  await login(page,user);await page.goto(`/jobs/${job.id}`);
  await page.getByRole('link',{name:'Prepare interview practice'}).click();
  await page.getByLabel('Practice source').selectOption(`cv:${resume.id}`);
  await page.getByLabel('Question count').fill('2');
  await page.getByRole('button',{name:'Review information to send'}).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button',{name:'Start interview',exact:true}).click();
  await expect(page).toHaveURL(/\/interviews\/[0-9a-f-]+$/);
  await page.getByRole('button',{name:'Ask first question (AI request)'}).click();
  await expect(page.getByRole('heading',{name:'Question 1 · behavioral'})).toBeVisible();
  if(voice){
    await page.getByLabel('Use optional voice controls').check();
    await expect(page.getByText('Synthetic test audio only; no live speech provider.',{exact:false})).toBeVisible();
    await page.getByRole('button',{name:'Start recording',exact:true}).click();
    await expect(page.getByText(/Recording microphone/)).toBeVisible();
    // Collect enough synthetic samples to exercise the real WAV encoder/parser.
    await page.waitForTimeout(1100);
    await page.getByRole('button',{name:'Stop recording',exact:true}).click();
    await expect(page.getByLabel('Recorded answer playback')).toBeVisible();
    await expect(page.getByRole('button',{name:'Send recording for transcription'})).toBeDisabled();
    await page.getByLabel('I agree to the described external audio and question processing.').check();
    const before=await (await request.get(`${API}/interviews/${page.url().split('/').at(-1)}`,{headers})).json();
    await page.getByRole('button',{name:'Send recording for transcription'}).click();
    await expect(page.getByLabel('Review transcript')).toHaveValue('I built a synthetic API and tested its error paths.');
    await expect(page.getByLabel('Your answer')).toHaveValue('');
    const after=await (await request.get(`${API}/interviews/${before.id}`,{headers})).json();
    expect(after.revision).toBe(before.revision);expect(after.turns).toEqual(before.turns);
    await page.getByLabel('Review transcript').fill('Reviewed: I tested a synthetic API.');
    await page.getByRole('button',{name:'Use reviewed transcript as answer draft'}).click();
    await expect(page.getByLabel('Your answer')).toHaveValue('Reviewed: I tested a synthetic API.');
    await page.getByRole('button',{name:'Generate spoken question'}).click();
    await expect(page.getByLabel('AI-generated question playback')).toBeVisible();
    await page.getByLabel('Mute generated speech').check();
    await page.getByRole('button',{name:'Stop spoken question'}).click();
  }
  const first='I built a booking API and checked error cases. I have no measured performance results.';
  await page.getByLabel('Your answer').fill(first);
  await page.getByRole('button',{name:'Save answer without AI'}).click();
  await expect(page.getByText('Answer saved. No model request was sent.')).toBeVisible();
  await page.reload();await expect(page.getByLabel('Your answer')).toHaveValue(first);
  await page.getByRole('button',{name:'Submit answer and continue'}).click();
  await expect(page.getByRole('heading',{name:'Question 2 · technical'})).toBeVisible();
  await page.getByLabel('Your answer').fill('I would compare query plans and test failure cases. This is a hypothetical approach.');
  await page.getByRole('button',{name:'Finish interview and review'}).click();
  await expect(page.getByRole('heading',{name:'Interview review',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Practice priorities'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'AI-generated guidance for answer 2'})).toBeVisible();
  await expect(page.getByText('Synthetic test provider — no live model assessment.',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Delete session',exact:true}).click();
  const deleted = page.waitForResponse(response => response.request().method() === 'DELETE' && response.url().includes('/api/interviews/'));
  await page.getByRole('button',{name:'Confirm delete session'}).click();
  expect((await deleted).status()).toBe(204);
  await expect(page).toHaveURL(`/jobs/${job.id}/interviews`, { timeout: 15_000 });
  await expect(page.getByText('No interview sessions yet.')).toBeVisible();
});
