"""add digest last_sent_at timestamp

Revision ID: ec844a9fd5fb
Revises: 8f376a4b2afd
Create Date: 2026-09-19 14:58:33.165748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec844a9fd5fb'
down_revision: Union[str, None] = '8f376a4b2afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digest_preferences', sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digest_preferences', 'last_sent_at')
    # ### end Alembic commands ###
