"""add review_notes to pack versions

Revision ID: a08de9e4bb9a
Revises: ea399de46402
Create Date: 2026-09-19 14:38:13.636486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a08de9e4bb9a'
down_revision: Union[str, None] = 'ea399de46402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_pack_versions', sa.Column('review_notes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_pack_versions', 'review_notes')
    # ### end Alembic commands ###
